import Head from "next/head";

export const Metadata = ({ title }) => {
  return (
    <div>
      <Head>
        <title>{title} | ChestWeather</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};
